version: "3"

services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]
